### ISSUE TITLE
There are no runnable files in the macOS version.

### ISSUE THREAD

**Issue by toosu** [Blondazz/KeyOverlay#24]
Hi, I just tried to launch it on macOS and opened the zip with the mac onboard app and other apps but the .app and other runnable files don't seem to exist.
here is picture of "ls -a" in terminal
![スクリーンショット 2021-12-16 20 49 37](https://user-images.githubusercontent.com/24892404/146367160-092672ce-0ce6-45c5-88ac-918ac4a98676.png)
thank you.

**Comment by toosu** [comment]
I'm going to describe my OS version and other information just in case.

macOS Mojave (10.14.6)
MacBook Pro (15-inch 2016)

**Comment by Blondazz** [comment]
I've changed the release for mac, can you please test if it works now?

**Comment by toosu** [comment]
I was able to confirm that a lot of files had been added, but there were no executable files yet. .app or .jar?

**Comment by Blondazz** [comment]
can you try running the executable with the name "KeyOverlay"?

**Comment by toosu** [comment]
I was unable to run "KeyOverlay". The file format is "Unix executable", which is not a format that can normally be opened on a mac.

**Comment by Blondazz** [comment]
Okay so you should be able to just do a ./KeyOverlay from the terminal or use "dotnet KeyOverlay.dll" on the previous release with dotnet installed and i think it should open. I don't have a mac and the emulators are ass so please check it yourself i'll send the previous version here again in case you deleted it
[KeyOverlay-macos-latest (1).zip](https://github.com/Blondazz/KeyOverlay/files/7780980/KeyOverlay-macos-latest.1.zip) 

Also please check this one as well if you have the time:
[osx-x64.zip](https://github.com/Blondazz/KeyOverlay/files/7780982/osx-x64.zip)
There is one file in the main folder and one in the publish folder idk which one should work tbh

**Comment by toosu** [comment]
I was not able to come here much during the New Year.

I tried it, but I get this error message.
`System.DllNotFoundException: Unable to load shared library 'csfml-system' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libcsfml-system, 1): image not found
   at SFML.System.Clock.sfClock_create()
   at KeyOverlay.AppWindow..ctor() in /Users/runner/work/KeyOverlay/KeyOverlay/AppWindow.cs:line 30
   at KeyOverlay.Program.Main(String[] args) in /Users/runner/work/KeyOverlay/KeyOverlay/Program.cs:line 13
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'csfml-system' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libcsfml-system, 1): image not found
   at SFML.System.Clock.sfClock_create()
   at KeyOverlay.AppWindow..ctor() in /Users/runner/work/KeyOverlay/KeyOverlay/AppWindow.cs:line 30
   at KeyOverlay.Program.Main(String[] args) in /Users/runner/work/KeyOverlay/KeyOverlay/Program.cs:line 13
Abort trap: 6`

**Comment by aeongdesu** [comment]
@toosu https://github.com/Blondazz/KeyOverlay/issues/25#issuecomment-1001641169

`brew install csfml` to fix this
