### ISSUE TITLE
Can't run on Linux

### ISSUE THREAD

**Issue by Sayykii** [Blondazz/KeyOverlay#25]
```
System.DllNotFoundException: Unable to load shared library 'csfml-system' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libcsfml-system: cannot open shared object file: No such file or directory
   at SFML.System.Clock.sfClock_create()
   at KeyOverlay.AppWindow..ctor() in /home/runner/work/KeyOverlay/KeyOverlay/AppWindow.cs:line 30
   at KeyOverlay.Program.Main(String[] args) in /home/runner/work/KeyOverlay/KeyOverlay/Program.cs:line 13
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'csfml-system' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libcsfml-system: cannot open shared object file: No such file or directory
   at SFML.System.Clock.sfClock_create()
   at KeyOverlay.AppWindow..ctor() in /home/runner/work/KeyOverlay/KeyOverlay/AppWindow.cs:line 30
   at KeyOverlay.Program.Main(String[] args) in /home/runner/work/KeyOverlay/KeyOverlay/Program.cs:line 13
zsh: abort (core dumped)  ./KeyOverlay
```

**Comment by Blondazz** [comment]
You have to find the csfml library using your package manager for you linux distribution and download it for it to work on linux

**Comment by Sayykii** [comment]
Yeah I tried doing that using aur, but it couldn't build for some reason.

**Comment by aMalteser** [comment]
The package is in the offical package manager, you can download the package using the command: `sudo pacman -S csfml`

**Comment by Sayykii** [comment]
Okay so it managed to build now, but I still get the same error.

**Comment by Sayykii** [comment]
Okay so it managed to build, but I still get the same error

**Comment by aMalteser** [comment]
There are [release files available.](https://github.com/Blondazz/KeyOverlay/releases/download/v1.0/KeyOverlay-linux-latest.zip) Extract into a folder, use `chmod` to make the file executable and run the `KeyOverlay` file.

**Comment by Sayykii** [comment]
Yeah I did that, same thing happens.
