### ISSUE TITLE
Special Characters not working

### ISSUE THREAD

**Issue by RyanC175** [Blondazz/KeyOverlay#27]
When I use characters such as ',' and '.' the program launches but closes immediately afterwards.

Error log:
```

> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
>    at System.Collections.Generic.List`1.get_Item(Int32 index)
>    at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
>    at KeyOverlay.AppWindow..ctor() in C:\Users\Daniel\source\KeyOverlay\AppWindow.cs:line 89
>    at KeyOverlay.Program.Main(String[] args) in C:\Users\Daniel\source\KeyOverlay\Program.cs:line 13
```

**Comment by Blondazz** [comment]
In case you closed it on accident:
![image](https://user-images.githubusercontent.com/35583718/152039719-bc7031e5-b465-4b6b-b760-deea91cf9dbb.png)
